name: learnova_app
description: "Learnova - AI powered tutoring platform."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  flutter_tts: ^4.0.2
  http: ^1.1.0
  shared_preferences: ^2.5.5
  speech_to_text: ^7.3.0
  flutter_math_fork: ^0.7.2
  fl_chart: ^0.68.0

dev_dependencies:
  cupertino_icons: ^1.0.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true



